describe('test', () => {
    it('Adding Items to the Card', () => {
        cy.visit('/')
        cy.fixture('product').then((p) => {
            cy.get('input#small-searchterms').click().type(p.product1)
            cy.get('input.button-1.search-box-button').click()
            cy.get('input.button-2.product-box-add-to-cart-button').click()
            cy.get('div#bar-notification.bar-notification.success').should('be.visible')
            cy.get('input#small-searchterms').clear().click().type(p.product4)
            cy.get('input.button-1.search-box-button').click()
            cy.get('input.button-2.product-box-add-to-cart-button').click()
            cy.get('div#bar-notification.bar-notification.success').should('be.visible')
            cy.get('input#small-searchterms').clear().click().type(p.product5)
            cy.get('input.button-1.search-box-button').click()
            cy.get('input.button-2.product-box-add-to-cart-button').click()
            cy.get('div#bar-notification.bar-notification.success').should('be.visible')
            cy.get('li#topcartlink').scrollIntoView().trigger('mouseover').should('be.visible')
            cy.get('li#topcartlink').click()
            cy.get('tbody').children('.cart-item-row').should('have.length.greaterThan', 0)
            cy.screenshot('cart')
        })
    })
    it('Remove Items From Cart', () => {
        cy.visit('/')
        cy.AddToCart()
        cy.get('li#topcartlink').click()
        cy.get('input[name="removefromcart"]').click({ multiple: true })
        cy.get('input[name="updatecart"]').click()
        cy.get('div.page-body').should('contain', 'Your Shopping Cart is empty!')
        cy.screenshot('cart-empty')
    })
})